export enum ConfigKeys {
  OPENAI_API_KEY = 'OPENAI_API_KEY',
  GEMINI_API_KEY = 'GEMINI_API_KEY',
  PORT = 'PORT',
  HOST = 'HOST',
  DEBUG = 'DEBUG',
  SWITCH_LATENCY_THRESHOLD_MS = 'SWITCH_LATENCY_THRESHOLD_MS',
  SWITCH_FAILURE_COUNT = 'SWITCH_FAILURE_COUNT',
  ACCOUNTS = 'ACCOUNTS',
  SYSTEM_TOKEN_KEY_CURRENT = 'SYSTEM_TOKEN_KEY_CURRENT',
  FIRESTORE_PROJECT_ID = 'FIRESTORE_PROJECT_ID',
  ENABLE_DB = 'ENABLE_DB'
}